name: crop-app-backend

services:
  postgres:
    image: postgres:15.6
    command: postgres -c 'max_connections=1000'
    restart: always
    hostname: "postgres"
    env_file:
      - .hatchet-user-env
    environment:
      - POSTGRES_USER=hatchet
      - POSTGRES_PASSWORD=o5T9P1w1B4xsA3PerOC3Q6BdOBqsPXjiQqePvfFG8YmOGwxTfzdyg1zOZehAt9cE
      - POSTGRES_DB=hatchet
    ports:
      - "5435:5432"
    volumes:
      - hatchet_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d hatchet -U hatchet"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5673:5672" # RabbitMQ
      - "15673:15672" # Management UI
    env_file:
      - .hatchet-user-env
    environment:
      RABBITMQ_DEFAULT_USER: "user-ar1HnF5kQrBNlFCG"
      RABBITMQ_DEFAULT_PASS: "MD6vTfxzkUtPvaCShcS4XBvytSB23i8izxV9k28ZTJRCkzkxOsq9pZiEXCyziqD1"
    volumes:
      - "hatchet_rabbitmq_data:/var/lib/rabbitmq"
      - "hatchet_rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf" # Configuration file mount
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
  migration:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-migrate:latest
    command: /hatchet/hatchet-migrate
    env_file:
      - .hatchet-user-env
    environment:
      DATABASE_URL: "postgresql://hatchet:o5T9P1w1B4xsA3PerOC3Q6BdOBqsPXjiQqePvfFG8YmOGwxTfzdyg1zOZehAt9cE@postgres:5432/hatchet?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
  setup-config:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-admin:latest
    command: /hatchet/hatchet-admin quickstart --skip certs --generated-config-dir /hatchet/config --overwrite=false
    env_file:
      - .hatchet-user-env
    environment:
      DATABASE_URL: postgresql://hatchet:o5T9P1w1B4xsA3PerOC3Q6BdOBqsPXjiQqePvfFG8YmOGwxTfzdyg1zOZehAt9cE@postgres:5432/hatchet?sslmode=disable
      SERVER_MSGQUEUE_RABBITMQ_URL: amqp://user-ar1HnF5kQrBNlFCG:MD6vTfxzkUtPvaCShcS4XBvytSB23i8izxV9k28ZTJRCkzkxOsq9pZiEXCyziqD1@rabbitmq:5672/
      SERVER_AUTH_COOKIE_DOMAIN: localhost:8080
      SERVER_AUTH_COOKIE_INSECURE: "t"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
      SERVER_GRPC_BROADCAST_ADDRESS: hatchet-engine:7070
      SERVER_DEFAULT_ENGINE_VERSION: "V1"
      SERVER_INTERNAL_CLIENT_INTERNAL_GRPC_BROADCAST_ADDRESS: hatchet-engine:7070
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
    depends_on:
      migration:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  hatchet-engine:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-engine:latest
    command: /hatchet/hatchet-engine --config /hatchet/config
    restart: on-failure
    depends_on:
      setup-config:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
    ports:
      - "7070:7070"
    expose:
      - "7070"
    env_file:
      - .hatchet-user-env
    environment:
      DATABASE_URL: "postgresql://hatchet:o5T9P1w1B4xsA3PerOC3Q6BdOBqsPXjiQqePvfFG8YmOGwxTfzdyg1zOZehAt9cE@postgres:5432/hatchet?sslmode=disable"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
  hatchet-dashboard:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-dashboard:latest
    command: sh ./entrypoint.sh --config /hatchet/config
    ports:
      - 8080:80
    env_file:
      - .hatchet-user-env
    restart: on-failure
    depends_on:
      setup-config:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "postgres://hatchet:o5T9P1w1B4xsA3PerOC3Q6BdOBqsPXjiQqePvfFG8YmOGwxTfzdyg1zOZehAt9cE@postgres:5432/hatchet"
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
 

  mongo-db:  # DB for backend
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: autocrop-db-user
      MONGO_INITDB_ROOT_PASSWORD: px2GsyO6HHEwbtWvmP4HEQHwXv7cAmzoQ4Xks8X171w4doQ5CHrGBXRG897B8ZXg
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  api:  # FastAPI backend
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #image: auto-crop-ml:uv
    image: ghcr.io/trineracz/orezy-backend-api:latest
    depends_on:
      mongo-db:
        condition: service_started
    command: uv run fastapi run --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .worker-env
    environment:
      ENABLE_TLS: "false"
      MONGODB_URI: "mongodb://autocrop-db-user:px2GsyO6HHEwbtWvmP4HEQHwXv7cAmzoQ4Xks8X171w4doQ5CHrGBXRG897B8ZXg@mongo-db:27017/mydb?authSource=admin"
      MONGODB_DB: "mydb"
      SCANS_VOLUME_PATH: "/upload_data"
      WEBAPP_TOKEN: "2fMRGgdFqWG1xJdPoiyVT6hKuwxKe2JmimxPbDtrmrpOUuW86uLwdGurVDxLPjPT"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    volumes:
      - scan_data:/upload_data

  worker:
    #image: auto-crop-ml:uv
    image: ghcr.io/trineracz/orezy-backend-worker:latest
    depends_on:
      api:
        condition: service_started
      hatchet-engine:
        condition: service_started
    command: uv run -m app.tasks.worker
    env_file:
      - .worker-env
    environment:
      ENABLE_TLS: "false"
      MONGODB_URI: "mongodb://autocrop-db-user:px2GsyO6HHEwbtWvmP4HEQHwXv7cAmzoQ4Xks8X171w4doQ5CHrGBXRG897B8ZXg@mongo-db:27017/mydb?authSource=admin"
      MONGODB_DB: "mydb"
    restart: unless-stopped
    volumes:
       - scan_data:/upload_data

volumes:
  hatchet_postgres_data:
  hatchet_rabbitmq_data:
  hatchet_rabbitmq.conf:
  hatchet_config:
  hatchet_certs:
  mongo_data:
  scan_data: