name: crop-app-backend

services:
  postgres:
    image: postgres:15.6
    command: postgres -c 'max_connections=1000'
    restart: always
    hostname: "postgres"
    env_file:
      - .admin-user-env
    environment:
      - POSTGRES_USER=hatchet
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=hatchet
    ports:
      - "5435:5432"
    volumes:
      - hatchet_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d hatchet -U hatchet"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5673:5672" # RabbitMQ
      - "15673:15672" # Management UI
    env_file:
      - .admin-user-env
    environment:
      RABBITMQ_DEFAULT_USER: "user-ar1HnF5kQrBNlFCG"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    volumes:
      - "hatchet_rabbitmq_data:/var/lib/rabbitmq"
      - "hatchet_rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf" # Configuration file mount
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
  migration:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-migrate:latest
    command: /hatchet/hatchet-migrate
    env_file:
      - .admin-user-env
    environment:
      DATABASE_URL: ${POSTGRES_URI}
    depends_on:
      postgres:
        condition: service_healthy
  setup-config:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-admin:latest
    command: /hatchet/hatchet-admin quickstart --skip certs --generated-config-dir /hatchet/config --overwrite=false
    env_file:
      - .admin-user-env
    environment:
      DATABASE_URL: ${POSTGRES_URI}
      SERVER_MSGQUEUE_RABBITMQ_URL: ${RABBITMQ_SERVER_URL}
      SERVER_AUTH_COOKIE_DOMAIN: localhost:8080
      SERVER_AUTH_COOKIE_INSECURE: "t"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
      SERVER_GRPC_BROADCAST_ADDRESS: hatchet-engine:7070
      SERVER_DEFAULT_ENGINE_VERSION: "V1"
      SERVER_INTERNAL_CLIENT_INTERNAL_GRPC_BROADCAST_ADDRESS: hatchet-engine:7070
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
    depends_on:
      migration:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  hatchet-engine:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-engine:latest
    command: /hatchet/hatchet-engine --config /hatchet/config
    restart: on-failure
    depends_on:
      setup-config:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
    ports:
      - "7070:7070"
    expose:
      - "7070"
    env_file:
      - .admin-user-env
    environment:
      DATABASE_URL: ${POSTGRES_URI}
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
  hatchet-dashboard:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-dashboard:latest
    command: sh ./entrypoint.sh --config /hatchet/config
    ports:
      - 8080:80
    env_file:
      - .admin-user-env
    restart: on-failure
    depends_on:
      setup-config:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: ${POSTGRES_URI}
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
 

  mongo-db:  # DB for backend
    image: mongo:8.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: autocrop-db-user
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:  # FastAPI backend
    image: trinera/smart-crop:1.0.0
    depends_on:
      mongo-db:
        condition: service_started
    command: uv run fastapi run --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .worker-env
      - .admin-user-env
    environment:
      WEBAPP_FRONTEND_URL: "*"
      ENABLE_TLS: false
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: mydb
      SCANS_VOLUME_PATH: /upload_data
      RETRAIN_VOLUME_PATH: /retrain_data
      WEBAPP_TOKEN: ${WEBAPP_TOKEN}
      PWD_SECRET: ${PWD_SECRET}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    volumes:
      - scan_data:/upload_data
      - retrain_data:/retrain_data

  worker:
    image: trinera/smart-crop:1.0.0
    depends_on:
      api:
        condition: service_started
      hatchet-engine:
        condition: service_started
    command: uv run -m app.tasks.worker
    env_file:
      - .worker-env
    environment:
      ENABLE_TLS: false
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: mydb
      RETRAIN_VOLUME_PATH: /retrain_data
    restart: unless-stopped
    volumes:
       - scan_data:/upload_data
  
  web-app:
    image: trinera/smart-crop-webapp:1.0.0
    command: npm run start
    ports:
      - "1234:80"
    environment:
      APP_DATA_SERVER_URL: http://localhost:8000
      APP_DEV_MODE: false
    restart: unless-stopped

volumes:
  hatchet_postgres_data:
  hatchet_rabbitmq_data:
  hatchet_rabbitmq.conf:
  hatchet_config:
  hatchet_certs:
  mongo_data:
  scan_data:
  retrain_data: